Add ui templates
etsauer/containers-quickstarts pull request #3
Opened 2018-11-01 23:04 UTC by tomgeorge

#### What is this PR About?
Describe the contents of the PR

#### How do we test this?
Provide commands/steps to test this PR.

cc: @redhat-cop/containerize-it

2018-11-05 14:58 UTC, etsauer requested changes
@tomgeorge

2018-11-05 14:58 UTC, etsauer commented on hygieia/.applier/group_vars/seed-hosts.yml
> +    - name: UI Builder Image
@tomgeorge could you combine these two builds into a single template, consistent with the others?

2018-11-05 14:58 UTC, etsauer commented on hygieia/.applier/group_vars/seed-hosts.yml
> +    - name: UI
same here. I think just one template called `deployment-ui`

2018-11-05 17:15 UTC, tomgeorge commented
@etsauer Consolidated the images and renamed `run-ui` to just `ui`.  Note this PR does not have API connectivity, that one is in #4

2018-11-06 01:46 UTC, etsauer approved these changes

2018-11-06 01:47 UTC, merged